# Generated by Django 5.1.4 on 2025-01-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='file_path',
            new_name='Location',
        ),
    ]
