# Generated by Django 5.1.4 on 2025-01-04 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapi', '0002_rename_file_path_uploadedpdf_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='documentapi.uploadedimage')),
            ],
        ),
    ]
