# Generated by Django 5.1.4 on 2025-01-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentapi', '0005_convertpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertpdf',
            name='convert_pdf',
        ),
    ]
