# Generated by Django 5.1.4 on 2025-01-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentapi', '0006_remove_convertpdf_convert_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerotation',
            name='rotated_image',
        ),
    ]
