# Generated by Django 5.1.4 on 2025-01-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapi', '0007_remove_imagerotation_rotated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerotation',
            name='rotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rotated_images/'),
        ),
    ]
